### ISSUE TITLE
Curl not recognizing SSL root certificates on RasPi 3

### ISSUE THREAD

**Issue by boeschmann** [dlueth/easyepg.minimal#1]
Hi all,

I've faced some difficulties when trying to configure easyepg using your docker images on a RasPi 3 running Kodi on Libreelec.

Here's what I did (multiply):
- Purge all docker images and repos from my RasPi
- Install the images using `sh -c "$(curl -s -H 'Cache-Control: no-cache https://raw.githubusercontent.com/dlueth/easyepg.minimal/master/init)"`
- Start the admin image using `docker start easyepg.admin`
- Trying to config easyepg using `docker exec -ti -w /easyepg easyepg.admin /bin/bash ./epg.sh`

The problems I ran into was that basically all services failed to create a channel list. Therefore, I 
- started a shell into the (still running) easyepg.admin container using `docker exec -ti -w /easyepg easyepg.admin /bin/bash`
- After fiddling around and checking outputs of sub-scripts manually, I ultimately found out that cURL seemes to cause problems when accessing HTTPS connections.
- `curl https://google.com` resulted in the error message
    > curl: (60) SSL certificate problem: unable to get local issuer certificate
    > More details here: https://curl.haxx.se/docs/sslcerts.html
    > 
    > curl failed to verify the legitimacy of the server and therefore could not
    > establish a secure connection to it. To learn more about this situation and
    > how to fix it, please visit the web page mentioned above.
- `wget https://google.com` however worked fine, so SSL in itself seemed to be working fine
- After fiddling around a bit more, forcing cURL to use the default crt file by issuing `export CURL_CA_BUNDLE="/etc/ssl/certs/ca-certificates.crt"` did the trick.

After setting CURL_CA_BUNDLE, I was able to configure easyepg just as I initially intended.

My questions are now:
- Is that behaviour of cURL known to anyone else?
- Do I (we) have a chance to change the docker config to set `CURL_CA_BUNDLE` according to above statement be default for all three images?
- If the answer to the last question is yes, can someone point me to the container configs? I'm happy to issue a pull request, I'm just not that familiar with docker yet.

Thanks a lot for your replies and comments.

Bests,
boeschmann

**Comment by dlueth** [comment]
Thanks for the report @boeschmann  - I am sure we'll be able to nail and fix your issue together ;)

AFAIK you seem to be the first one facing this issue. It sounds like a very simple problem with ca-certficates but I just want to make sure that I implement the right fix. Hope you do not mind some questions:

1. Have you been using the image before (without issues) or is this your first usage? (Image was switched from Debian Stretch to Buster a couple of days ago, so this might be a possible cause)
2. Does entering the container as root and issue `apt-get update && apt-get install ca-certificates` fix the problem as well, without the need for the `export CURL_CA_BUNDLE="/etc/ssl/certs/ca-certificates.crt"` you mentioned above?

Kind regards,
Dirk

**Comment by dlueth** [comment]
Could not reproduce the issue on my local machine with neither the debian-buster nor beta alpine-based image but there seem to be people that have similar problems anyway. So implemented the proposed fix by adding `CURL_CA_BUNDLE="/etc/ssl/certs/ca-certificates.crt"` as an env-var to `Dockerfile.multi`?

Build via GitHub actions for "latest" is already running

**Comment by boeschmann** [comment]
Hi Dirk,

to answer your questions:
1. I had been using the image without problems before
2. Executing `apt-get update && apt-get install ca-certificates` as root within the container did not fix the problem. apt-get's statement was that ca-certificates already had been installed, and was already at the latest version as well.

Thanks a lot for the update! HTTPS access for cURL seems to be working now :-)

Bests,
Gerhard
