### ISSUE TITLE
Please update the alpine image

### ISSUE THREAD

**Issue by Akruidenberg** [dlueth/easyepg.minimal#2]
Current image is more than 500MB in size, the alpine image is updated 7 months ago. Alpine is al lot smaller and better for security purposes.

**Comment by dlueth** [comment]
Alpine did not work on all host-systems though - but it did work for me... I'll have a look ;)

**Comment by dlueth** [comment]
@Akruidenberg Updated and tested the alpine image to latest alpine. It works on my machine but feedback would be nice to get ;)

If it works I will look into enabling the autobuild once a week - it should be enabled but it might only work for workflows in master branch whereas alpine is on its own branch.

You should be able to get an update with the docker tag `latest-alpine`

**Comment by dlueth** [comment]
@Akruidenberg report from your side would be greatly appreciated - the new alpine version ran perfectly fine on my macbook but failed on my linux pvr tonight. Looking into it...

**Comment by dlueth** [comment]
I'll be closing this die to lack of feedback. Although I have an alpine based version ready it has some problems I was unable to resolve :(

**Comment by Akruidenberg** [comment]
Sorry for my late reaction. I´m a little busy with life. latest:alpine is working fine with my config. It´s working the same as the latest tag.
Using Ziggo Netherlands. Do you need more feedback?
