### ISSUE TITLE
Container contains critical vulnerabilities

### ISSUE THREAD

**Issue by m4tt075** [dlueth/easyepg.minimal#5]
Coud you please update the base image of your container? It is pretty outdated and contains several security vulnerabilities, which have been fixed in the meantime.

**Comment by etofi** [comment]
The last image on Docker Hub is from 19.12.2021.
Is it fixed in this version?

**Comment by m4tt075** [comment]
I actually believe this has been my mistake in the meantime. The base image is based on debian buster, which still obtains security patches regularly. When you install the container, it pulls all the security fixes and applies them. The issues only occur if you don't update the container for a long time. I didn't do that, because there were no changes to easyepg itself. Therefore, the base image simply fell behind. If you recreate the container regularly, you should always receive the latest updates and shouldn't have problems. You just have to recreate it from time to time, even if easyepg is unchanged.

Sorry for the noise. Closing the issue accordingly.
