### ISSUE TITLE
Cron alle x Stunden

### ISSUE THREAD

**Issue by etofi** [dlueth/easyepg.minimal#6]
Unfortunately I can't use FREQUENCY="0 */3 * *" (so every 3 hours) because then the container crashes on startup.
Is it possible to fix this?

**Comment by etofi** [comment]
I think the problem can be found in the file "entrypoint".
Here "/" is used as sed separator. 
If you change this to "|" it should work I think.

**Comment by dlueth** [comment]
Thanks for the report @etofi - should be fixed now, build just started
